import { defineConfig } from "drizzle-kit";

/**
 * Drizzle Kit reads `DATABASE_URL` from the shell. Run via:
 *   `pnpm db:generate` and `pnpm db:migrate` — both pass
 *   `--env-file=.env.local` so the shell sees the local URL without
 *   pulling in `dotenv`.
 *
 * Migrations split between two folders:
 *   - `server/db/migrations/` — generated by drizzle-kit from the schema.
 *   - `server/db/migrations/_manual/` — hand-written SQL (RLS policies,
 *     triggers, extensions, PII comments). Drizzle-kit ignores it; we
 *     apply it through `pnpm db:migrate` (see `scripts/migrate.ts`).
 */
export default defineConfig({
  schema: "./server/db/schema/index.ts",
  out: "./server/db/migrations",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL ?? "",
  },
  strict: true,
  verbose: true,
  casing: "snake_case",
});
