-- Auto-generated by `drizzle-kit generate` after the schema change in
-- 0015_invoices_soft_delete.sql. Both migrations describe the same
-- diff (deleted_at column + partial unique index); 0015 ran first on
-- DBs that received it, so 0016 must be idempotent against that state.
--
-- Guards on every statement:
--   - `DROP INDEX IF EXISTS`             — safe whether 0015 already replaced it.
--   - `ADD COLUMN IF NOT EXISTS`         — Postgres 9.6+ supports this directly.
--   - `CREATE UNIQUE INDEX IF NOT EXISTS` — re-create only if missing.

DROP INDEX IF EXISTS "invoices_attorney_period_uniq";--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "deleted_at" timestamp with time zone;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "invoices_attorney_period_uniq" ON "invoices" USING btree ("attorney_id","period_year","period_month") WHERE "invoices"."deleted_at" is null;
