import Link from "next/link";
import { redirect } from "next/navigation";
import { auth } from "@/server/auth/config";
import { api } from "@/lib/trpc/server";
import { APP_ROUTES, pageTitle } from "@/config";
import { formatCents } from "@/lib/utils";

export const metadata = { title: pageTitle("Settings") };

/**
 * Stage 10 attorney settings — billing tab. Shows the 85/15 split
 * note + a paginated list of past invoices generated by Docket.
 *
 * "Past invoices" reads `revenue.myInvoices` which is RLS-scoped to
 * the caller, so even an admin viewing this page sees only their own
 * invoices (admin invoice browser lives at /admin/revenue). Each row
 * deep-links to the Stripe-hosted invoice URL when the invoice is
 * `open` / `paid`. `failed` invoices show the failure reason inline
 * so the attorney knows to update payment method in Stripe before
 * the next finalize attempt.
 *
 * Future tabs (House style, Team, etc.) live behind sidebar links
 * but aren't wired in Phase 1 — the mockup includes them; we render
 * the heading slots so navigation reads correctly even while the
 * sub-pages are stubs.
 */
export default async function SettingsPage(): Promise<React.ReactElement> {
  const session = await auth();
  if (!session?.user) redirect(APP_ROUTES.login);

  const me = await api.me.current();
  if (!me) redirect(APP_ROUTES.authError + "?error=session-mismatch");

  const summary = await api.revenue.attorneySummary();
  const { items: invoiceRows } = await api.revenue.myInvoices({});

  return (
    <main className="mx-auto max-w-4xl px-6 py-12 space-y-8">
      <header>
        <p
          className="text-xs uppercase tracking-[0.3em]"
          style={{ color: "var(--ink-muted, rgba(0,0,0,0.5))" }}
        >
          Settings
        </p>
        <h1
          className="mt-2 text-3xl tracking-tight"
          style={{ fontFamily: "var(--font-serif), Georgia, serif" }}
        >
          Partnership &amp; billing
        </h1>
        <p
          className="mt-1 text-sm"
          style={{ color: "var(--ink-muted)" }}
        >
          Your revenue split with Docket and a list of past monthly invoices.
        </p>
      </header>

      <section
        className="rounded-md border p-5"
        style={{
          borderColor: "var(--accent, var(--ink))",
          background: "var(--accent-soft, var(--surface-sunken, #f5f1e9))",
        }}
      >
        <div className="flex items-baseline gap-4">
          <span
            className="text-5xl tracking-tight"
            style={{ fontFamily: "var(--font-serif), Georgia, serif", color: "var(--accent, var(--ink))" }}
          >
            85<span className="text-2xl">%</span>
          </span>
          <div>
            <h2 className="text-base font-medium">You keep 85% of every case fee.</h2>
            <p className="mt-1 text-sm" style={{ color: "var(--ink-soft)" }}>
              Docket&rsquo;s 15% is deducted from each filing &mdash; never added on top, never charged
              before the package is approved and exported. Invoiced once monthly.
            </p>
          </div>
        </div>
      </section>

      <section>
        <h2 className="text-sm font-medium uppercase tracking-wide" style={{ color: "var(--ink-muted)" }}>
          Lifetime Docket share
        </h2>
        <dl className="mt-3 grid grid-cols-3 gap-4 text-sm">
          <SummaryStat label="Pending (not yet invoiced)" cents={summary.totals.pendingCents} />
          <SummaryStat label="Invoiced (open)" cents={summary.totals.invoicedCents} />
          <SummaryStat label="Paid" cents={summary.totals.paidCents} />
        </dl>
      </section>

      <section>
        <header className="mb-3 flex items-baseline justify-between">
          <h2 className="text-sm font-medium uppercase tracking-wide" style={{ color: "var(--ink-muted)" }}>
            Past invoices
          </h2>
          <span className="text-xs" style={{ color: "var(--ink-muted)" }}>
            {invoiceRows.length} {invoiceRows.length === 1 ? "invoice" : "invoices"}
          </span>
        </header>

        {invoiceRows.length === 0 ? (
          <p
            className="rounded-md border border-dashed p-6 text-center text-sm"
            style={{ borderColor: "var(--border)", color: "var(--ink-muted)" }}
          >
            No invoices yet. Docket invoices the 15% share on the 1st of each month
            for cases filed the prior month.
          </p>
        ) : (
          <table className="w-full text-sm">
            <thead className="text-left text-xs uppercase tracking-wide" style={{ color: "var(--ink-muted)" }}>
              <tr>
                <th className="pb-2 font-medium">Period</th>
                <th className="pb-2 font-medium">Amount</th>
                <th className="pb-2 font-medium">Status</th>
                <th className="pb-2 font-medium">Created</th>
                <th className="pb-2 font-medium" />
              </tr>
            </thead>
            <tbody>
              {invoiceRows.map((row) => (
                <tr
                  key={row.id}
                  className="border-t"
                  style={{ borderColor: "var(--border)" }}
                >
                  <td className="py-3 mono text-xs">
                    {periodLabel(row.periodYear, row.periodMonth)}
                  </td>
                  <td className="py-3 mono">{formatCents(row.totalCents)}</td>
                  <td className="py-3 text-xs">
                    <InvoiceStatusPill status={row.status} />
                  </td>
                  <td className="py-3 text-xs" style={{ color: "var(--ink-muted)" }}>
                    {new Date(row.createdAt).toLocaleDateString()}
                  </td>
                  <td className="py-3 text-right text-xs">
                    {row.hostedInvoiceUrl ? (
                      <Link
                        href={row.hostedInvoiceUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="underline-offset-2 hover:underline"
                      >
                        View &rarr;
                      </Link>
                    ) : (
                      <span style={{ color: "var(--ink-muted)" }}>—</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>
    </main>
  );
}

function SummaryStat({
  label,
  cents,
}: {
  label: string;
  cents: bigint;
}): React.ReactElement {
  return (
    <div
      className="rounded-md border p-4"
      style={{ borderColor: "var(--border)", background: "var(--surface)" }}
    >
      <p className="text-[10px] uppercase tracking-wider" style={{ color: "var(--ink-muted)" }}>
        {label}
      </p>
      <p
        className="mt-2 text-xl tracking-tight"
        style={{ fontFamily: "var(--font-serif), Georgia, serif" }}
      >
        {formatCents(cents)}
      </p>
    </div>
  );
}

function periodLabel(year: number, month: number): string {
  const d = new Date(Date.UTC(year, month - 1, 1));
  return d.toLocaleString("en-US", {
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}

function InvoiceStatusPill({
  status,
}: {
  status: "draft" | "open" | "paid" | "void" | "uncollectible" | string;
}): React.ReactElement {
  const palette: Record<string, { bg: string; fg: string }> = {
    paid: { bg: "var(--success-soft, #e7f3ec)", fg: "var(--success, #1f6b3d)" },
    open: { bg: "var(--surface-sunken, #f4efe5)", fg: "var(--ink)" },
    draft: { bg: "var(--surface-sunken, #f4efe5)", fg: "var(--ink-muted)" },
    void: { bg: "var(--surface-sunken, #f4efe5)", fg: "var(--ink-muted)" },
    uncollectible: { bg: "var(--warning-soft, #fbeede)", fg: "var(--warning, #8a4a13)" },
  };
  const palette$ = palette[status] ?? palette["open"]!;
  return (
    <span
      className="rounded-sm px-2 py-0.5 text-[10px] uppercase tracking-wider"
      style={{ background: palette$.bg, color: palette$.fg }}
    >
      {status}
    </span>
  );
}
