import "server-only";
import { inngest } from "@/server/jobs/client";
import { sendEmail } from "@/server/services/email";
import { caseBuildCompletedEvent } from "@/server/jobs/case-build";
import { caseOutputsUrl, resolveCaseRecipient } from "./recipient";

/**
 * `case/build.completed` listener — emits the case-build-completed
 * email. The trigger is the orchestrator's existing domain event (no
 * dedicated `notification/*` event needed); the listener owns recipient
 * resolution + Postmark dispatch.
 *
 * Idempotency: Inngest sends the event once per orchestrator run; the
 * concurrency key on `caseId` plus retries=2 means a flaky send retries
 * but the same event id never produces two emails.
 *
 * Why we read `successCount` from the event rather than re-counting
 * outputs: at email-send time the case might already have new versions
 * regenerated by an attorney click — the count we want is "outputs
 * produced by THIS build run", which only the event has.
 */
export const caseBuildCompletedNotification = inngest.createFunction(
  {
    id: "notification-case-build-completed",
    concurrency: { key: "event.data.caseId", limit: 1 },
    retries: 2,
    triggers: [{ event: caseBuildCompletedEvent }],
  },
  async ({ event, step }) => {
    const { caseId, successCount } = event.data;

    const recipient = await step.run("resolve-recipient", async () =>
      resolveCaseRecipient(caseId),
    );
    if (!recipient) {
      console.info("[notification.case.build_completed] no recipient", {
        caseId,
      });
      return { delivered: "skipped" as const, reason: "no recipient" };
    }

    const result = await step.run("send", async () =>
      sendEmail({
        to: recipient.email,
        email: {
          name: "case.build_completed",
          props: {
            attorneyName: recipient.name,
            caseLabel: recipient.caseLabel,
            outputCount: successCount,
            outputsUrl: caseOutputsUrl(caseId),
          },
        },
      }),
    );
    if (result.delivered === "failed") {
      throw new Error(`case.build_completed send failed: ${result.error}`);
    }
    return result;
  },
);
