import type { CaseStatus } from "@/lib/case-status";
import { PIPELINE_STATUSES, type PipelineKey } from "@/lib/pipeline";

/**
 * Single source of truth for "what stage is this case in, and what
 * does the attorney do next?" Mapped from the 14-value
 * `caseStatusEnum` to the 5-bucket `PIPELINE_STATUSES` vocabulary plus
 * a human label, optional sub-line, optional next-action CTA, and a
 * 0..100 progress percentage for visual bars.
 *
 * Replaces three older mappers that drifted as the enum evolved:
 *   - `dashboard/page.tsx::stageFor` (label + percent)
 *   - `dashboard/page.tsx::nextActionFor` (CTA only)
 *   - `me.ts::taskLabelFor` / `taskSubFor` (today-tasks rail copy)
 *
 * Pure over `(status, approvals)` so the dashboard server component,
 * the `me.todayTasks` tRPC procedure, and the client-side
 * `CaseStageRail` can all share one derivation. Adding a new status
 * means updating one switch, not three.
 */

export type CaseStageInput = {
  status: CaseStatus;
  /** Approval tally — only consulted when `status === "in_review"` to
   *  enrich the label with "X/Y approved". Optional everywhere else. */
  approvals?: { approved: number; total: number };
};

export type CaseStage = {
  /** Pipeline-bucket key. Same vocabulary as `lib/pipeline.ts`. */
  pipelineKey: PipelineKey;
  /** Short label — "Drafts ready", "In review · 2/5". */
  label: string;
  /** Secondary copy used by the today-tasks rail and the case-stage
   *  rail's hint line. Empty string for terminal / no-context states. */
  sub: string;
  /** CTA label suggesting the next attorney action. `undefined` for
   *  no-action states (extracting, building, archived, filed). */
  nextAction: string | undefined;
  /** Visual progress hint, 0..100. */
  progressPct: number;
};

const PIPELINE_BY_STATUS: Map<CaseStatus, PipelineKey> = (() => {
  const out = new Map<CaseStatus, PipelineKey>();
  for (const [key, statuses] of Object.entries(PIPELINE_STATUSES)) {
    for (const s of statuses) out.set(s, key as PipelineKey);
  }
  return out;
})();

export function deriveCaseStage(input: CaseStageInput): CaseStage {
  const { status, approvals } = input;
  // `archived` is terminal and lives outside `PIPELINE_STATUSES` (it's
  // intentionally excluded — archived cases shouldn't bucket into any
  // active stage). Default to `filed` for the rail's last-step
  // rendering and call it out explicitly in the label.
  const pipelineKey: PipelineKey =
    PIPELINE_BY_STATUS.get(status) ?? "filed";

  switch (status) {
    case "intake":
      return {
        pipelineKey,
        label: "Intake",
        sub: "Enter beneficiary information.",
        nextAction: "Complete intake form",
        progressPct: 8,
      };
    case "documents_pending":
      return {
        pipelineKey,
        label: "Documents pending",
        sub: "Awaiting evidence uploads.",
        nextAction: "Upload evidence",
        progressPct: 22,
      };
    case "extracting":
      return {
        pipelineKey,
        label: "Extracting documents",
        sub: "Reading uploaded files — usually under a minute.",
        nextAction: undefined,
        progressPct: 32,
      };
    case "ready_to_build":
      return {
        pipelineKey,
        label: "Ready to build",
        sub: "Required documents collected.",
        nextAction: "Click Build",
        progressPct: 42,
      };
    case "building":
      return {
        pipelineKey,
        label: "Building drafts",
        sub: "Drafting petition, personal statement, and exhibits.",
        nextAction: undefined,
        progressPct: 55,
      };
    case "build_failed":
      return {
        pipelineKey,
        label: "Build failed",
        sub: "Pipeline error — see case for details.",
        nextAction: "Retry build",
        progressPct: 50,
      };
    case "draft_ready":
      return {
        pipelineKey,
        label: "Drafts ready",
        sub: "Generated by Docket — awaiting your review.",
        nextAction: "Review drafts",
        progressPct: 65,
      };
    case "in_review": {
      const hasApprovals = approvals && approvals.total > 0;
      return {
        pipelineKey,
        label: hasApprovals
          ? `In review · ${approvals.approved}/${approvals.total}`
          : "In review",
        sub: hasApprovals
          ? `${approvals.approved} of ${approvals.total} outputs approved.`
          : "Reviewing generated outputs.",
        nextAction: "Continue review",
        progressPct: 75,
      };
    }
    case "needs_revision":
      return {
        pipelineKey,
        label: "Needs revision",
        sub: "You marked outputs as needing changes.",
        nextAction: "Apply revisions",
        progressPct: 70,
      };
    case "approved":
      return {
        pipelineKey,
        label: "Approved",
        sub: "All outputs approved — ready to package.",
        nextAction: "Download package",
        progressPct: 88,
      };
    case "package_ready":
      return {
        pipelineKey,
        label: "Package ready",
        sub: "Combined PDF compiled and ready to download.",
        nextAction: "Download package",
        progressPct: 92,
      };
    case "delivered":
      return {
        pipelineKey,
        label: "Delivered",
        sub: "Package downloaded — file with USCIS when ready.",
        nextAction: "Mark filed",
        progressPct: 96,
      };
    case "filed":
      return {
        pipelineKey,
        label: "Filed with USCIS",
        sub: "Receipt recorded. Awaiting adjudication.",
        nextAction: undefined,
        progressPct: 100,
      };
    case "archived":
      return {
        pipelineKey,
        label: "Archived",
        sub: "Soft-deleted. Restore via admin tools.",
        nextAction: undefined,
        progressPct: 100,
      };
  }
}
